version: '3.9'
services:
  app:
    build: .
    image: 'laravelapp'
    ports:
      - 8080:80
    volumes:
      - ./app_logs/:/var/log/apache2
  db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./database-logs:/var/lib/mysql/
